# Ensemble Learning

## Initial Imports

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

## Read the CSV and Perform Basic Data Cleaning

In [4]:
# Load the data
file_path = Path('Resources/LoanStats_2019Q1.csv')
df = pd.read_csv(file_path)

# Preview the data
df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

In [5]:
# Find non numeric columns which might require binary encoding
non_numeric_columns = df.select_dtypes(exclude=['int','float']).columns.tolist()
non_numeric_columns

['home_ownership',
 'verification_status',
 'issue_d',
 'loan_status',
 'pymnt_plan',
 'initial_list_status',
 'next_pymnt_d',
 'application_type',
 'hardship_flag',
 'debt_settlement_flag']

In [6]:
#for loop to count the values of non numeric columns

for column in non_numeric_columns:
    print(df[column].value_counts())

MORTGAGE    36219
RENT        24613
OWN          7346
ANY           639
Name: home_ownership, dtype: int64
Not Verified       32895
Source Verified    25737
Verified           10185
Name: verification_status, dtype: int64
Jan-2019    31041
Feb-2019    25579
Mar-2019    12197
Name: issue_d, dtype: int64
low_risk     68470
high_risk      347
Name: loan_status, dtype: int64
n    68817
Name: pymnt_plan, dtype: int64
w    60292
f     8525
Name: initial_list_status, dtype: int64
May-2019    42449
Apr-2019    26368
Name: next_pymnt_d, dtype: int64
Individual    59206
Joint App      9611
Name: application_type, dtype: int64
N    68817
Name: hardship_flag, dtype: int64
N    68817
Name: debt_settlement_flag, dtype: int64

In [7]:
#drop columns with one category and dates as it will not add any value
df=df.drop(columns=["pymnt_plan",
                    "hardship_flag",
                    "debt_settlement_flag"
                    ],
           axis=1)
df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,dti,delinq_2yrs,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,27.24,0.0,...,0.0,3.0,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,20.23,0.0,...,0.0,6.0,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,24.26,0.0,...,0.0,4.0,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,31.44,0.0,...,0.0,1.0,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,18.76,0.0,...,0.0,1.0,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0

In [8]:
# Binary encoding using Pandas for home_ownership and verification_status
df = pd.get_dummies(df, columns=["home_ownership",
                                 "verification_status",
                                 "initial_list_status",
                                 "application_type",
                                 "issue_d",
                                 "next_pymnt_d"
                                ])
df.head()

,loan_amnt,int_rate,installment,annual_inc,loan_status,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,...,verification_status_Verified,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,issue_d_Feb-2019,issue_d_Jan-2019,issue_d_Mar-2019,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019
0,10500.0,0.1719,375.35,66000.0,low_risk,27.24,0.0,0.0,8.0,0.0,...,0,0,1,1,0,0,0,1,0,1
1,25000.0,0.2000,929.09,105000.0,low_risk,20.23,0.0,0.0,17.0,1.0,...,1,0,1,1,0,0,0,1,0,1
2,20000.0,0.2000,529.88,56000.0,low_risk,24.26,0.0,0.0,8.0,0.0,...,1,0,1,1,0,0,0,1,0,1
3,10000.0,0.1640,353.55,92000.0,low_risk,31.44,0.0,1.0,10.0,1.0,...,1,0,1,1,0,0,0,1,0,1
4,22000.0,0.1474,520.39,52000.0,low_risk,18.76,0.0,1.0,14.0,0.0,...,0,0,1,1,0,0,0,1,0,1

## Split the Data into Training and Testing

In [9]:
# Create our features
X = df.drop(columns = 'loan_status')

# Create our target
y = df['loan_status']

In [10]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,verification_status_Verified,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,issue_d_Feb-2019,issue_d_Jan-2019,issue_d_Mar-2019,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.148001,0.123879,0.876121,0.860340,0.139660,0.371696,0.451066,0.177238,0.383161,0.616839
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.355104,0.329446,0.329446,0.346637,0.346637,0.483261,0.497603,0.381873,0.486161,0.486161
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [11]:
# Check the balance of our target values
y.value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [12]:
# Split the X and y into X_train, X_test, y_train, y_test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, random_state=1, stratify=y)

## Data Pre-Processing

Scale the training and testing data using the `StandardScaler` from `sklearn`. Remember that when scaling the data, you only scale the features data (`X_train` and `X_testing`).

In [13]:
# Create the StandardScaler instance
from sklearn.preprocessing import StandardScaler
data_scaler = StandardScaler()

In [14]:
# Fit the Standard Scaler with the training data
# When fitting scaling functions, only train on the training dataset
data_scaler.fit(X_train)

StandardScaler()

In [15]:
# Scale the training and testing data
X_train_scaled = data_scaler.transform(X_train)
X_test_scaled = data_scaler.transform(X_test)
display(X_train_scaled[:5])
display(X_test_scaled[:5])

array([[-0.64978133, -0.30327574, -0.52669276, -0.3724324 ,  0.12734932,
        -0.30466134, -0.65734502, -0.42798869,  2.58702132, -0.50717341,
        -0.21563307, -0.6727715 , -0.67230992, -0.02259602, -0.02241936,
         0.04583923, -0.2826692 , -0.03171854,  0.        ,  0.        ,
        -0.23063686, -0.12022901,  0.        ,  0.        ,  1.41091527,
         0.66408731,  0.83810521, -0.43717302,  0.15941501,  0.05861428,
        -0.88921398,  0.12509742, -0.77059663, -0.1601867 , -0.24622699,
        -0.461267  , -0.79685003, -0.65956457, -0.89659529, -0.24071567,
        -0.91344373, -0.26090134,  0.86486281, -0.54872097, -0.33695922,
        -0.07812619, -0.00769495, -0.00931849,  0.49562425, -0.64710392,
        -0.82768702, -0.25583179, -0.67610119,  1.54023396, -0.33774962,
        -0.73070032, -0.76040267, -0.66013244, -0.74386823, -0.19863987,
        -0.32036507, -0.06221464, -0.7613889 , -0.42553381,  0.        ,
         0.        , -0.1351054 , -0.11378866,  0.59175288, -0.91229847,
         2.58746462,  0.        ,  0.51332437, -0.09170382, -0.75733047,
        -0.03294137, -0.09759955,  0.94255244, -0.34381364, -0.74237524,
        -0.95471711,  1.28724062, -0.41477832, -0.37643971,  0.37643971,
         0.40497582, -0.40497582, -0.76806284,  1.10309558, -0.46513025,
        -0.78908914,  0.78908914],
       [ 0.42378352, -0.42616892,  0.71269346, -0.29160806,  0.60300788,
        -0.30466134, -0.65734502, -0.09609996, -0.37432858,  0.04844842,
        -0.62139263,  0.34223671,  0.34245748,  0.86349942,  0.86366781,
         0.82715604,  0.4632593 , -0.03171854,  0.        ,  0.        ,
         0.20643784, -0.12022901,  0.        ,  0.        , -0.10541046,
        -0.74835095, -0.86744979, -0.43717302, -0.86943676,  0.05861428,
        -0.0226565 , -0.52821235, -0.54679588, -0.84126057, -1.04548911,
         0.02405263, -1.06740191,  0.69139053,  0.39873638, -0.58842955,
        -0.91344373, -0.89692808, -0.71422822,  1.47419207, -0.7463699 ,
        -0.07812619, -0.00769495, -1.39943754, -1.07784614,  0.66834929,
         1.08202124, -0.8280524 ,  0.25547708,  1.04386764, -0.33774962,
         1.29600352,  0.68149659,  1.19441158,  1.00159375, -0.85803867,
         0.27223339,  0.06256278,  0.679712  , -0.09356109,  0.        ,
         0.        , -0.1351054 , -1.16977358,  0.59175288, -0.91229847,
        -0.37426135,  0.        , -0.58610476, -0.44760726,  1.3046767 ,
        -0.50474625, -0.09759955, -1.06094892, -0.34381364,  1.34702769,
         1.04743069, -0.77685553, -0.41477832, -0.37643971,  0.37643971,
         0.40497582, -0.40497582, -0.76806284,  1.10309558, -0.46513025,
        -0.78908914,  0.78908914],
       [ 1.79013878, -0.82400957,  2.19335392,  0.8880424 , -0.89879586,
        -0.30466134,  1.99174464, -0.92582179, -0.37432858, -0.77075879,
        -0.45908881,  1.64685734,  1.64676858,  1.91003815,  1.91019676,
         1.70799684,  1.51249351, -0.03171854,  0.        ,  0.        ,
         0.7285989 , -0.12022901,  0.        ,  0.        , -0.10541046,
         0.38722806, -0.86744979, -0.77587596, -0.86943676, -1.23614283,
         4.31013093, -0.86089769, -3.00860408, -0.84126057, -0.24622699,
        -0.9576047 , -2.90715469, -0.02049   , -0.24892946, -0.58842955,
        -0.08085229, -0.89692808,  1.19123332,  1.16159307, -1.6470734 ,
        -0.07812619, -0.00769495, -0.16768648,  0.04462955, -0.07516774,
         0.92287889,  1.46083003, -0.3655751 , -1.27250852, -0.33774962,
        -1.13604109, -1.33716237, -0.66013244,  0.34704551, -0.98991843,
        -0.91296353, -0.06221464, -1.33782926, -0.92349289,  0.        ,
         0.        , -0.1351054 , -1.16977358, -0.04594643, -0.91229847,
        -0.37426135,  0.        ,  0.61093621, -1.04470431,  0.438036  ,
        -0.57928896, -0.09759955, -1.06094892,  2.90855246, -0.74237524,
         1.04743069, -0.77685553, -0.41477832, -0.37643971,  0.37643971,
         0.40497582, -0.40497582, -0.76806284,  1.10309558, -0.46513025,
        -0.78908914,  0.78908914],
       [ 0.32618671, -0.95315156,  0.51679744, -0.0741521 ,  0.22124184,
        -0.30466134, -0.65734502,  0.40173314, -0.37432858, -0.68912258,
         0.43358221,  0.30221019,  0.30244045,  0.22634998,  0.22652432,
         0.29229911, -0.18119836, -0.03171854,  0.        ,  0.        ,
         0.13735429, -0.12022901,  0.        ,  0.        , -0.10541046,
        -0.48323262, -0.86744979,  0.57893581, -0.86943676,  0.70599283,
        -0.09486962,  0.70244139, -0.32299514, -0.1601867 , -0.64585805,
        -0.88240202, -0.63451891, -0.28474868, -0.24892946,  0.10699822,
        -0.49714801, -0.26090134, -0.55925315, -0.21394069, -1.25902327,
        -0.07812619, -0.00769495, -0.16768648, -0.63687355, -0.41832945,
        -0.03197524, -0.25583179,  0.16231925, -0.11432044, -0.33774962,
        -0.32535955, -0.47202281, -0.35104177, -0.52568548,  0.85639822,
         0.27223339, -0.06221464, -0.47316872,  0.40439798,  0.        ,
         0.        , -0.1351054 , -0.64178112, -0.61145337, -0.91229847,
        -0.37426135,  0.        , -0.34937637,  0.33943194, -0.57055446,
         1.08712967, -0.09759955, -1.06094892,  2.90855246, -0.74237524,
        -0.95471711,  1.28724062, -0.41477832, -0.37643971,  0.37643971,
         0.40497582, -0.40497582,  1.30197681, -0.90653976, -0.46513025,
        -0.78908914,  0.78908914],
       [-0.39602964,  0.16538471, -0.18156751, -0.16074961,  0.02440117,
         1.11320892,  1.99174464, -0.92582179, -0.37432858, -0.39277258,
         0.19012648, -0.39841181, -0.39801533, -0.10101955, -0.10084217,
        -0.07530765, -0.14013873, -0.03171854,  0.        ,  0.        ,
        -0.108927  , -0.12022901,  0.        ,  0.        , -0.10541046,
         0.62679402,  1.69088271, -0.09847008,  2.21711857,  2.00074994,
        -0.88921398, -0.38138116, -0.90487708, -0.84126057, -1.04548911,
         0.48296388, -0.63451891, -0.43036061,  2.34173388,  0.80242598,
         0.75173915,  0.3751254 ,  1.56470099,  0.0212692 , -0.50072349,
        -0.07812619, -0.00769495,  1.34560767,  2.61028827,  1.12589824,
        -0.82768702,  3.17749186,  0.28652969, -0.94159764,  0.3880366 ,
        -1.13604109, -1.33716237, -0.66013244, -0.52568548,  0.5926387 ,
        -1.11049635, -0.9356566 , -1.33782926, -0.92349289,  0.        ,
         0.        , -0.1351054 ,  0.94219627, -0.74380606, -0.91229847,
        -0.37426135,  0.        ,  0.552615  , -0.48698086, -0.12229203,
        -0.1112278 , -0.09759955,  0.94255244, -0.34381364, -0.74237524,
        -0.95471711,  1.28724062, -0.41477832, -0.37643971,  0.37643971,
         0.40497582, -0.40497582,  1.30197681, -0.90653976, -0.46513025,
        -0.78908914,  0.78908914]])

array([[-1.23536216, -1.196855  , -1.24170452, -0.7698957 ,  0.84655651,
        -0.30466134, -0.65734502, -1.58959925, -0.37432858, -0.80912184,
        -1.35175982, -1.23347867, -1.23288407, -0.49027494, -0.49009392,
        -0.3176014 , -0.87264252, -0.03171854,  0.        ,  0.        ,
        -0.48278872, -0.12022901,  0.        ,  0.        , -0.10541046,
        -0.60864983, -0.86744979, -0.77587596, -0.86943676, -0.58876428,
        -0.09486962, -0.66422271,  0.70648829, -0.84126057, -1.04548911,
        -1.10381271, -0.25574628, -0.92921628, -0.24892946, -0.58842955,
        -0.91344373, -1.21494145,  0.36200528, -0.44134787, -1.71827525,
        -0.07812619, -0.00769495, -1.98012018,  0.06467376,  0.61115568,
         0.92287889, -0.25583179,  1.24916058,  0.8784122 , -0.33774962,
        -1.54138186, -1.62554222, -1.27831377, -0.74386823, -1.12179819,
        -1.50556199, -0.9356566 , -1.62604944, -1.58743832,  0.        ,
         0.        , -0.1351054 , -1.16977358,  0.59175288, -0.91229847,
        -0.37426135,  0.        , -0.60143134, -0.88892405, -0.81336327,
        -0.855719  , -0.09759955,  0.94255244, -0.34381364, -0.74237524,
        -0.95471711, -0.77685553,  2.41092638, -0.37643971,  0.37643971,
        -2.46928324,  2.46928324, -0.76806284,  1.10309558, -0.46513025,
        -0.78908914,  0.78908914],
       [ 0.22858991,  0.06540381, -0.16370179, -0.43497504, -0.87544188,
        -0.30466134, -0.65734502, -0.75987742, -0.37432858, -0.76984101,
        -0.62139263,  0.27827972,  0.27851565, -0.44934661, -0.44916597,
        -0.3854522 , -0.42130793, -0.03171854,  0.        ,  0.        ,
        -0.10262658, -0.12022901,  0.        ,  0.        , -0.10541046,
        -0.82069784, -0.01467229, -0.77587596, -0.86943676, -1.23614283,
         0.98832724, -0.41964408,  1.64645142,  0.52088718,  0.15340406,
        -0.95410691, -0.25574628, -0.47889792, -0.89659529,  1.49785375,
         1.16803488, -0.57891471, -0.71823785,  0.13006544, -1.56875135,
        -0.07812619, -0.00769495, -0.59000113, -1.26826613, -0.76149116,
        -0.98682937, -0.8280524 , -0.73820641, -0.7761422 , -0.33774962,
        -1.13604109, -1.33716237, -0.35104177, -0.52568548, -0.46239939,
        -0.32036507, -0.31176949, -1.33782926, -0.75750653,  0.        ,
         0.        , -0.1351054 , -0.11378866,  0.59175288, -0.91229847,
        -0.37426135,  0.        , -0.85774773, -0.66237866, -0.34642324,
        -0.67522151, -0.09759955,  0.94255244, -0.34381364, -0.74237524,
        -0.95471711, -0.77685553,  2.41092638, -0.37643971,  0.37643971,
        -2.46928324,  2.46928324, -0.76806284, -0.90653976,  2.1499354 ,
        -0.78908914,  0.78908914],
       [-0.45458772,  0.35493183, -0.68932999, -0.53600546,  0.08588409,
        -0.30466134, -0.65734502, -0.26204433,  2.58702132, -0.37941893,
        -0.62139263, -0.41476455, -0.41436419, -0.56509411, -0.56491239,
        -0.46425242, -0.61203884, -0.03171854,  0.        ,  0.        ,
        -0.26428822, -0.12022901,  0.        ,  0.        , -0.10541046,
        -0.85085793, -0.86744979, -0.77587596, -0.86943676, -0.58876428,
        -0.09486962, -0.69324492,  0.84076873, -0.84126057,  0.15340406,
        -0.55063577, -0.85096041, -0.18497755,  0.39873638, -0.58842955,
         0.33544343, -0.26090134, -0.79874851,  0.22988119, -1.11661956,
        -0.07812619, -0.00769495, -1.59299842, -0.9776251 ,  0.09641311,
         0.92287889, -0.8280524 , -0.17925945,  0.051135  ,  0.3880366 ,
         1.29600352,  0.96987644,  0.88532091,  0.56522825, -0.72615891,
         0.27223339, -0.18699207,  0.96793218, -0.25954745,  0.        ,
         0.        , -0.1351054 , -1.16977358, -0.15423499, -0.53966714,
         2.58746462,  0.        , -0.85960755, -0.75191292, -0.13723411,
        -0.89471597, -0.09759955, -1.06094892, -0.34381364,  1.34702769,
         1.04743069, -0.77685553, -0.41477832, -0.37643971,  0.37643971,
         0.40497582, -0.40497582,  1.30197681, -0.90653976, -0.46513025,
         1.26728394, -1.26728394],
       [ 0.1309931 ,  0.06540381,  0.44261815, -0.49751768,  0.30512551,
        -0.30466134, -0.65734502, -0.92582179, -0.37432858, -0.38423726,
        -1.27060791,  0.15945459,  0.15971872, -0.3174447 , -0.31726529,
        -0.2207658 , -0.50431979, -0.03171854,  0.        ,  0.        ,
         0.11119466, -0.12022901,  0.        ,  0.        , -0.10541046,
        -0.8634154 ,  0.83810521, -0.77587596, -0.86943676, -0.58876428,
         0.69947474, -0.73420804, -1.08391767,  0.52088718, -0.24622699,
        -0.58386486, -0.74273966, -0.51664916, -0.24892946, -0.58842955,
        -0.91344373, -0.57891471, -0.75833407, -0.29402885, -0.60752628,
        -0.07812619, -0.00769495, -0.36124737, -0.73709459, -0.64710392,
        -0.66854466, -0.8280524 , -0.67610119,  1.54023396, -0.33774962,
        -0.32535955, -0.18364296, -0.66013244, -0.74386823, -0.98991843,
        -0.51789789, -0.81087917, -0.18494854, -0.92349289,  0.        ,
         0.        , -0.1351054 , -0.11378866, -2.079365  , -0.91229847,
        -0.37426135,  0.        , -0.89763746, -0.78919144, -0.51452165,
        -0.79722354, -0.09759955, -1.06094892, -0.34381364,  1.34702769,
         1.04743069, -0.77685553, -0.41477832, -0.37643971,  0.37643971,
         0.40497582, -0.40497582, -0.76806284, -0.90653976,  2.1499354 ,
        -0.78908914,  0.78908914],
       [ 2.2781228 , -0.07623579,  1.45500877,  1.80212717, -0.564691  ,
         1.11320892, -0.65734502,  0.40173314, -0.37432858,  1.45195798,
         1.16394941,  2.40670239,  2.40643335, -0.79125594, -0.79107211,
        -0.58662777, -1.11143105, -0.03171854,  0.        ,  0.        ,
        -0.63452689, -0.12022901,  0.        ,  0.        , -0.10541046,
         2.17529389, -0.86744979,  0.91763875, -0.86943676, -0.58876428,
         0.19398287, -0.06919738, -0.68107633, -0.84126057, -0.24622699,
         2.63883239,  0.06891598,  1.12822631, -0.89659529,  0.4547121 ,
        -0.91344373,  0.3751254 ,  1.53746101, -0.41749809,  1.16896007,
        -0.07812619, -0.00769495,  0.7121357 ,  0.96666315, -0.01797412,
         1.08202124,  2.60527125,  0.10021404,  2.36751116, -0.33774962,
        -0.32535955,  0.10473689, -0.66013244, -0.96205098,  1.77955655,
        -0.32036507, -0.43654691,  0.10327164,  0.40439798,  0.        ,
         0.        , -0.1351054 , -1.16977358,  0.27891926,  1.0760623 ,
        -0.37426135,  0.        ,  2.17181405,  0.47931731,  0.56130817,
         0.32577228, -0.09759955,  0.94255244, -0.34381364, -0.74237524,
        -0.95471711, -0.77685553,  2.41092638, -0.37643971,  0.37643971,
        -2.46928324,  2.46928324, -0.76806284, -0.90653976,  2.1499354 ,
        -0.78908914,  0.78908914]])

## Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Display the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier only, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [16]:
# Resample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
brf_model = BalancedRandomForestClassifier(n_estimators=100, random_state=78)
brf_model = brf_model.fit(X_train_scaled, y_train)

In [17]:
# Calculated the balanced accuracy score
y_pred_brf = brf_model.predict(X_test_scaled)
balanced_accuracy_score(y_test, y_pred_brf)

0.7831230283911672

In [18]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred_brf)

array([[   58,    29],
       [ 1719, 15399]])

In [19]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred_brf))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.03      0.67      0.90      0.06      0.77      0.59        87
   low_risk       1.00      0.90      0.67      0.95      0.77      0.61     17118

avg / total       0.99      0.90      0.67      0.94      0.77      0.61     17205

In [20]:
# List the features sorted in descending order by feature importance
importances_sorted_brf = sorted(zip(brf_model.feature_importances_, X.columns), reverse=True)
importances_sorted_brf

[(0.08107901444883758, 'total_rec_prncp'),
 (0.0734948453918542, 'last_pymnt_amnt'),
 (0.06126614939524893, 'total_rec_int'),
 (0.04745732727314766, 'total_pymnt'),
 (0.046888502454432025, 'total_pymnt_inv'),
 (0.02353680500196841, 'int_rate'),
 (0.019687239246330115, 'issue_d_Jan-2019'),
 (0.019181128183860807, 'installment'),
 (0.0184993693798729, 'max_bal_bc'),
 (0.017256397613776786, 'dti'),
 (0.017019244788225286, 'out_prncp_inv'),
 (0.016629146268492868, 'annual_inc'),
 (0.01661427476851829, 'revol_bal'),
 (0.01659930896921667, 'out_prncp'),
 (0.015158929272714658, 'tot_hi_cred_lim'),
 (0.015126164861195501, 'total_bal_il'),
 (0.014962480208874454, 'bc_open_to_buy'),
 (0.014680974985981868, 'avg_cur_bal'),
 (0.014303966392371067, 'mths_since_recent_inq'),
 (0.013897259855314073, 'mo_sin_old_rev_tl_op'),
 (0.013829290842247464, 'all_util'),
 (0.013790497451153001, 'total_rev_hi_lim'),
 (0.013678704862608297, 'total_il_high_credit_limit'),
 (0.01342957822345465, 'issue_d_Mar-2019'),
 (0.013328006554817536, 'tot_cur_bal'),
 (0.012664004747305346, 'bc_util'),
 (0.012554114785096278, 'total_bal_ex_mort'),
 (0.012510811937168406, 'mo_sin_old_il_acct'),
 (0.012281702732726588, 'mths_since_rcnt_il'),
 (0.011956547903287144, 'il_util'),
 (0.011876470848260498, 'total_bc_limit'),
 (0.01147242958505482, 'mo_sin_rcnt_rev_tl_op'),
 (0.011197233303078653, 'loan_amnt'),
 (0.010961423665390184, 'num_actv_bc_tl'),
 (0.010895990614415981, 'mths_since_recent_bc'),
 (0.010895865614714636, 'inq_last_12m'),
 (0.00991845893833123, 'total_cu_tl'),
 (0.00974161903997594, 'total_acc'),
 (0.00971607418162407, 'num_bc_tl'),
 (0.009383080798918595, 'pct_tl_nvr_dlq'),
 (0.009320927480994896, 'num_op_rev_tl'),
 (0.009275321994532059, 'acc_open_past_24mths'),
 (0.008886748013778319, 'num_rev_tl_bal_gt_0'),
 (0.008749586605492026, 'num_actv_rev_tl'),
 (0.008531517799928246, 'open_acc'),
 (0.008106256989619965, 'num_bc_sats'),
 (0.00805379814249895, 'num_sats'),
 (0.007996871743164517, 'num_rev_accts'),
 (0.0077681120242049494, 'open_act_il'),
 (0.0076045337435564535, 'mo_sin_rcnt_tl'),
 (0.007506926963044828, 'num_il_tl'),
 (0.007367609480210539, 'total_rec_late_fee'),
 (0.007350079144490806, 'percent_bc_gt_75'),
 (0.007089249667680363, 'inq_fi'),
 (0.006847333434919611, 'num_tl_op_past_12m'),
 (0.006569528632314307, 'open_il_24m'),
 (0.005677362425011321, 'inq_last_6mths'),
 (0.005480078520757232, 'open_rv_24m'),
 (0.00526817977108932, 'delinq_2yrs'),
 (0.005261792320774515, 'next_pymnt_d_May-2019'),
 (0.0051915448465393215, 'mort_acc'),
 (0.005151830329037243, 'open_il_12m'),
 (0.004543079617367811, 'issue_d_Feb-2019'),
 (0.004200348695199178, 'open_rv_12m'),
 (0.004199558913903291, 'open_acc_6m'),
 (0.003977858600250004, 'next_pymnt_d_Apr-2019'),
 (0.0027737181412756016, 'tot_coll_amt'),
 (0.002746733929518228, 'verification_status_Not Verified'),
 (0.00247983962046733, 'num_accts_ever_120_pd'),
 (0.001817339175873721, 'verification_status_Verified'),
 (0.0017557790640269674, 'pub_rec'),
 (0.001672883893771684, 'verification_status_Source Verified'),
 (0.001539584124398059, 'home_ownership_RENT'),
 (0.0014372338811883378, 'home_ownership_MORTGAGE'),
 (0.0013549757031591583, 'num_tl_90g_dpd_24m'),
 (0.00131586230529213, 'home_ownership_OWN'),
 (0.0013043911568377754, 'application_type_Individual'),
 (0.0012150396761231844, 'initial_list_status_w'),
 (0.0011184342528783198, 'pub_rec_bankruptcies'),
 (0.0010121449188492317, 'initial_list_status_f'),
 (0.0007327025043845453, 'application_type_Joint App'),
 (0.00032686636173231975, 'collections_12_mths_ex_med'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'home_ownership_ANY'),
 (0.0, 'delinq_amnt'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'chargeoff_within_12_mths'),
 (0.0, 'acc_now_delinq')]

### Easy Ensemble Classifier

In [21]:
# Train the Classifier
from imblearn.ensemble import EasyEnsembleClassifier 
eec_model = EasyEnsembleClassifier(n_estimators=100, random_state=78)
eec_model = eec_model.fit(X_train_scaled, y_train)

In [22]:
# Calculated the balanced accuracy score
y_pred_eec = eec_model.predict(X_test_scaled)
balanced_accuracy_score(y_test, y_pred_eec)

0.9274135715177813

In [23]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred_eec)

array([[   79,     8],
       [  911, 16207]])

In [24]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred_eec))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.08      0.91      0.95      0.15      0.93      0.86        87
   low_risk       1.00      0.95      0.91      0.97      0.93      0.86     17118

avg / total       0.99      0.95      0.91      0.97      0.93      0.86     17205

### Final Questions

1. Which model had the best balanced accuracy score?

   Easy ensemble classifier has best balanced accuracy score.

   |S.N.|Approach|Balanced Accuracy Score|
   |:---|:-----:|-------------:|
   |1|Balanced Random Forest Classifier|0.7831230283911672|
   |2|Easy Ensemble Classifier|0.9274135715177813|

2. Which model had the best recall score?

   Easy ensemble classifier has best recall score.

   |S.N.|Approach|Recall Score|
   |:---|:-----:|-------------:|
   |1|Balanced Random Forest Classification|0.90|
   |2|Easy Ensemble Classifier|0.95|

3. Which model had the best geometric mean score?

   Easy ensemble classifier has geometric mean score.

   |S.N.|Approach|Geometric Mean Score|
   |:---|:-----:|-------------:|
   |1|Balanced Random Forest Classifier|0.77|
   |2|Easy Ensemble Classifier|0.93|

4. What are the top three features?

   Top three features based on balanced random forest classifier are 
   
   |S.N.|Feature|Importance|
   |:---|:-----:|-------------:|
   |1|total_rec_prncp|0.08107901444883758|
   |2|last_pymnt_amnt|0.0734948453918542|
   |3|total_rec_int|0.06126614939524893|